### PR TITLE
Data #1

### PR DESCRIPTION
**Pull request by lhendey**

### CODE REVIEW

**Comment by lhendey** [comment]
@rpitingolo - can you review today? This is just the base read in for the tract level files. I need to use them for the MVT profile.

**Comment by rpitingolo** [comment]
@lhendey I can review in about a half hour.

**Comment by rpitingolo** [comment]
@lhendey I reviewed and it seems to work fine. One question I have is about why you chose to use %tr10_to_stdgeos? I assume this is to later create summary files, in which case  %Transform_geo_data should work for that purpose. I created %tr10_to_stdgeos to run in a legacy program where summary files get created via proc means. The more accurate way of creating summary files is to use %Transform_geo_data (or Create_all_summary_from_tracts.sas if you want to do them all at once). %tr10_to_stdgeos doesn't take any weighting into account.

**Comment by lhendey** [comment]
@rpitingolo good point. i'll remove it.

**Pull request merged**
